### ISSUE TITLE
Import Error with Theano

### ISSUE THREAD

**Issue by agude** [Lab41/attalos#43]
Splitting from #40.

## Import Error (perhaps in TF but definitely in Theano):

Appears to be a GFortran & BLAS issue in scipy, though compiled was okay prior Anaconda migration. Issue doesn't appear to be problematic in notebooks, but in bash shell, will not compile.

Here is the error:

```
ImportError: ('The following error happened while compiling the node', Dot22(InplaceDimShuffle{1,0}.0, InplaceDimShuffle{1,0}.0), '\n', "/opt/conda/lib/python2.7/site-packages/scipy/special/../../../../libgfortran.so.3: version `GFORTRAN_1.4' not found (required by /usr/lib/libblas.so.3)", '[Dot22(<TensorType(float64, matrix)>, <TensorType(float64, matrix)>)]')
```

To reproduce, simply try to compile any of the code in imgtxt_algorithms in karllab41 fork master branch.

**Comment by ymt123** [comment]
I'll try it with the code from the branch when I get back. When I tried the Theano GPU sample code it worked ok. I know i've had problems with setting the THEANO_FLAGS for floatx to be float32...
